# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:      
  packer_init_validate:
    runs-on: ubuntu-latest
    name: Validate Packer for the AMI Build
    steps: 
      - name: Step 1 - Checkout code from branch
        uses: actions/checkout@v2

      - name: Step 2 - zip all the webapp files
        run: |
          zip -r webapp.zip ./
          pwd ./webapp

      - name: Step 3 - Validate Packer Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ami.pkr.hcl

